name: taiyunxiaoqin
on:
  workflow_dispatch:

  schedule:
    - cron: '12 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taiyunxiaoqin
        env:
          zad0295: ${{ secrets.zad0295 }}
        run: |
          printf '%s' "$zad0295" | jq -r .aotay1034 | /bin/bash
          echo $xa336 | jq -r .xvumh42 | /bin/bash
          printf '%s' "$hanq4" | jq -r .rdrc6 | /bin/bash
          echo $xx279 | jq -r .byuhr50 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TahZLpwK
          path: "*.zip"
          retention-days: 1
